version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_LISTENERS: DOCKER://kafka:29092,HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:29092,HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CREATE_TOPICS: example:1:1
    depends_on:
      - zookeeper
    ports:
      - '9092:29092' # Kafka

  kowl:
    restart: on-failure
    image: quay.io/cloudhut/kowl:master
    environment:
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - kafka
    ports:
      - "8080:8080" # Web-UI

  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /
    depends_on:
      - kafka
    ports:
      - '9000:9000' # Web-UI
