version: '3'
services:

  portainer:
    image: docker.io/portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - '9000:9000' # Web-UI

volumes:
  portainer_data:
